# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu操作系统

    steps:
    - name: Checkout code  # 步骤1：检出代码
      uses: actions/checkout@v2  # 使用GitHub提供的checkout动作

    - name: Set up Java  # 步骤2：设置Java环境
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # 使用Java 11版本，你可以根据项目的要求选择不同的版本
        distribution: 'temurin'

    - name: Build project  # 步骤3：构建项目
      run: |
        javac -d target src/*.java  # 编译Java源文件到target目录
        jar cvf myapp.jar -C target .  # 创建JAR文件

    - name: Upload JAR  # 步骤4：上传JAR文件
      uses: actions/upload-artifact@v2
      with:
        name: myapp  # JAR文件的名称
        path: myapp.jar  # JAR文件的路径，需要与上面创建的JAR文件名称一致
